### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
print(tf.__version__)

2.10.1


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[88, 376, 230, 29], [88, 376, 230, 347], [88, 65, 230, 361], [122, 27, 13, 69, 83], [122, 27, 13, 69, 465], [434, 88, 375, 230, 302], [311, 39, 8, 69]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  88 376 230  29]
 [  0   0   0   0  88 376 230 347]
 [  0   0   0   0  88  65 230 361]
 [  0   0   0 122  27  13  69  83]
 [  0   0   0 122  27  13  69 465]
 [  0   0   0 434  88 375 230 302]
 [  0   0   0   0 311  39   8  69]]


In [9]:
## 10 feature dimesnions
dim=10


In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  88, 376, 230,  29])

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 381ms/step


array([[ 0.02029626,  0.00239952, -0.03624066, -0.02999287, -0.04864559,
        -0.02907615,  0.04608455, -0.02301415,  0.01143373, -0.00497011],
       [ 0.02029626,  0.00239952, -0.03624066, -0.02999287, -0.04864559,
        -0.02907615,  0.04608455, -0.02301415,  0.01143373, -0.00497011],
       [ 0.02029626,  0.00239952, -0.03624066, -0.02999287, -0.04864559,
        -0.02907615,  0.04608455, -0.02301415,  0.01143373, -0.00497011],
       [ 0.02029626,  0.00239952, -0.03624066, -0.02999287, -0.04864559,
        -0.02907615,  0.04608455, -0.02301415,  0.01143373, -0.00497011],
       [ 0.02242053, -0.03302477, -0.03548118,  0.00825365,  0.01017165,
        -0.03077551, -0.00912595, -0.03202907, -0.02400893, -0.01429557],
       [ 0.03061518,  0.02239876,  0.02581665, -0.01685908, -0.02182983,
         0.04871901, -0.01318206, -0.01749374,  0.04050862, -0.02659167],
       [ 0.03867935, -0.02852326, -0.01281691, -0.02071002,  0.00719004,
         0.01768387, -0.02530088, -0.0342098 

In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 37ms/step
[[[ 2.02962644e-02  2.39951536e-03 -3.62406597e-02 -2.99928673e-02
   -4.86455932e-02 -2.90761478e-02  4.60845493e-02 -2.30141524e-02
    1.14337318e-02 -4.97011095e-03]
  [ 2.02962644e-02  2.39951536e-03 -3.62406597e-02 -2.99928673e-02
   -4.86455932e-02 -2.90761478e-02  4.60845493e-02 -2.30141524e-02
    1.14337318e-02 -4.97011095e-03]
  [ 2.02962644e-02  2.39951536e-03 -3.62406597e-02 -2.99928673e-02
   -4.86455932e-02 -2.90761478e-02  4.60845493e-02 -2.30141524e-02
    1.14337318e-02 -4.97011095e-03]
  [ 2.02962644e-02  2.39951536e-03 -3.62406597e-02 -2.99928673e-02
   -4.86455932e-02 -2.90761478e-02  4.60845493e-02 -2.30141524e-02
    1.14337318e-02 -4.97011095e-03]
  [ 2.24205293e-02 -3.30247656e-02 -3.54811773e-02  8.25364515e-03
    1.01716518e-02 -3.07755116e-02 -9.12594795e-03 -3.20290700e-02
   -2.40089297e-02 -1.42955668e-02]
  [ 3.06151770e-02  2.23987587e-02  2.58166529e-02 -1.68590769e-02
   -2.18298323e-02  4.87190150e

In [15]:
embedded_docs[0]

array([  0,   0,   0,   0,  88, 376, 230,  29])

In [16]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 21ms/step
[[ 0.02029626  0.00239952 -0.03624066 -0.02999287 -0.04864559 -0.02907615
   0.04608455 -0.02301415  0.01143373 -0.00497011]
 [ 0.02029626  0.00239952 -0.03624066 -0.02999287 -0.04864559 -0.02907615
   0.04608455 -0.02301415  0.01143373 -0.00497011]
 [ 0.02029626  0.00239952 -0.03624066 -0.02999287 -0.04864559 -0.02907615
   0.04608455 -0.02301415  0.01143373 -0.00497011]
 [ 0.02029626  0.00239952 -0.03624066 -0.02999287 -0.04864559 -0.02907615
   0.04608455 -0.02301415  0.01143373 -0.00497011]
 [ 0.02242053 -0.03302477 -0.03548118  0.00825365  0.01017165 -0.03077551
  -0.00912595 -0.03202907 -0.02400893 -0.01429557]
 [ 0.03061518  0.02239876  0.02581665 -0.01685908 -0.02182983  0.04871901
  -0.01318206 -0.01749374  0.04050862 -0.02659167]
 [ 0.03867935 -0.02852326 -0.01281691 -0.02071002  0.00719004  0.01768387
  -0.02530088 -0.0342098  -0.01895839 -0.03448746]
 [ 0.03536462  0.04706389 -0.00980454 -0.00549782 -0.01783664  0.01851923

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]